
apiVersion: v1
kind: Service
metadata:
  name: chaincode-as-external-service
  namespace: distributedweb-io
spec:
  type: ClusterIP
  selector:
    chaincode: chaincode-demo
  ports:
  - name: "listen"
    port: 9999
    protocol: TCP
    targetPort: 9999
