OrdererOrgs:
  - Name: Orderer
    Domain: distributedweb.io
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer0
        SANS:
          - localhost
          - 127.0.0.1
          - ::1
          - orderer0-distributedweb-io
          - orderer0-distributedweb-io.distributedweb-io.svc.cluster.local
          - orderer0.distributedweb.io
      - Hostname: orderer1
        SANS:
          - localhost
          - 127.0.0.1
          - ::1
          - orderer1-distributedweb-io
          - orderer1-distributedweb-io.distributedweb-io.svc.cluster.local
          - orderer1.distributedweb.io
      - Hostname: orderer2
        SANS:
          - localhost
          - 127.0.0.1
          - ::1
          - orderer2-distributedweb-io
          - orderer2-distributedweb-io.distributedweb-io.svc.cluster.local
          - orderer2.distributedweb.io
PeerOrgs:
  - Name: Org1
    Domain: org1.distributedweb.io
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
        - 127.0.0.1
        - ::1
        - "{{.Hostname}}-org1-distributedweb-io"
        - "{{.Hostname}}-org1-distributedweb-io.distributedweb-io.svc.cluster.local"
        - "{{.Hostname}}.org1.distributedweb.io"
    Users:
      Count: 1
  - Name: Org2
    Domain: org2.distributedweb.io
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
        - 127.0.0.1
        - ::1
        - "{{.Hostname}}-org2-distributedweb-io"
        - "{{.Hostname}}-org2-distributedweb-io.distributedweb-io.svc.cluster.local"
        - "{{.Hostname}}.org2.distributedweb.io"
    Users:
      Count: 1
  - Name: Org3
    Domain: org3.distributedweb.io
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
        - 127.0.0.1
        - ::1
        - "{{.Hostname}}-org3-distributedweb-io"
        - "{{.Hostname}}-org3-distributedweb-io.distributedweb-io.svc.cluster.local"
        - "{{.Hostname}}.org3.distributedweb.io"
    Users:
      Count: 1
