resources:
  - services/ordering-service.yaml
  - services/org1.distributedweb.io/peer0.yaml
  - services/org2.distributedweb.io/peer0.yaml
  - services/org3.distributedweb.io/peer0.yaml
  - services/chaincodes/demo.yaml
  - statefulsets/ordering-service.yaml
  - statefulsets/org1.distributedweb.io/peer0.yaml
  - statefulsets/org2.distributedweb.io/peer0.yaml
  - statefulsets/org3.distributedweb.io/peer0.yaml
  - deployments/chaincodes/demo.yaml
  - deployments/org1.distributedweb.io/cli.yaml
  - deployments/org2.distributedweb.io/cli.yaml
