apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chaincode-buildpack
  namespace: distributedweb-io
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
